LOOKBACK_YEARS = 5
TRADING_DAYS_PER_YEAR = 252
DT = 1 / TRADING_DAYS_PER_YEAR

JUMP_THRESHOLD_STD = 3.0
HESTON_ROLLING_WINDOW = 20
CORRELATION_WINDOW_DAYS = 90
CORRELATION_STRESS_PERCENTILE = 0.75
CORRELATION_STRESS_RATIO_SPAN = 1.0
SYSTEMIC_JUMP_FRACTION = 0.2

BACKTEST_YEARS = 2
BACKTEST_STEP_DAYS = 10
BACKTEST_N_PATHS = 20_000
BACKTEST_N_SEEDS = 5
BACKTEST_MIN_HISTORY_DAYS = 260

HORIZON_DAYS = 10
HORIZON_DAYS_LONG = TRADING_DAYS_PER_YEAR
N_SIMULATION_PATHS = 500_000
N_SIMULATION_SEEDS = 20

VAR_CONFIDENCE_LEVELS = [0.95, 0.99]

KELLY_FRACTION = 0.5
KELLY_MAX_F = 0.25
RISK_FREE_RATE_FALLBACK = 0.04

HOLDINGS_PATH = "holdings.json"
CANDIDATES_PATH = "candidates.json"
PRICE_CACHE_DIR = "state/prices"
PARAMS_CACHE_PATH = "state/calibrated_params.json"
